fix wrong param in grepping dss status

diff --git a/contrib/checkbox-dss-validation/checkbox-provider-dss/bin/check_dss b/contrib/checkbox-dss-validation/checkbox-provider-dss/bin/check_dss
--- a/contrib/checkbox-dss-validation/checkbox-provider-dss/bin/check_dss
+++ b/contrib/checkbox-dss-validation/checkbox-provider-dss/bin/check_dss
@@ -28,10 +28,10 @@ check_dss_namespace_is_deployed() {
 
 check_dss_status_contains() {
     result=$(dss status) # save result to shell var to avoid broken pipe error
-    if echo "${result}" | grep -q "${0}"; then
-        echo "Test success: 'dss status' shows '$0'."
+    if echo "${result}" | grep -q "${1}"; then
+        echo "Test success: 'dss status' shows '$1'."
     else
-        >&2 echo "Test failure: 'dss status' does not show '$0'."
+        >&2 echo "Test failure: 'dss status' does not show '$1'."
         exit 1
     fi
 }
